data_cfg:
  dataset_name: OUMVLP
  dataset_root: ../OU-MVLP_AlphaPose17
  dataset_partition: ./datasets/OUMVLP/OUMVLP.json
  test_dataset_name: OUMVLP
  num_workers: 2
  remove_no_gallery: false

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 70000
  save_name: gagformer_17
  sampler:
    batch_size: 8 #should same to num_gpus
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos
  eval_func: evaluate_indoor_dataset
  transform:
    - type: Compose
      trf_cfg:
        - type: GaitTR_MultiInput
          joint_format: coco
        - type: SkeletonInput

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.3
    type: TripletLoss
    log_prefix: triplet
    is_hard_loss: true
  - loss_term_weight: 0.5
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
    label_smooth: false

model_cfg:
  model: GagFormer
  in_c:
    - 10
    - 64
    - 128
    - 128
    - 128
    - 256
    - 256
    - 256
  num_class: 5153
  share_num: 4
  joint_format: coco


optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.00002

scheduler_cfg:
  three_phase: True
  max_lr: 0.001
  div_factor: 100
  total_steps: 100000
  pct_start: 0.475 #学习率上升部分的比例
  scheduler: OneCycleLR

trainer_cfg:
  enable_float16: false #not use
  log_iter: 100
  with_test: false
  restore_ckpt_strict: false
  restore_hint: 0
  save_iter: 10000
  save_name: gagformer_17 # 每次的记录名称
  sync_BN: true
  total_iter: 100000
  sampler:
    batch_shuffle: false
    batch_size:
      - 32
      - 16
    frames_num_fixed: 30
    frames_num_max: 30
    frames_num_min: 0
    sample_type: fixed_unordered #Repeat sample
    frames_skip_num: 0 
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: NormalizeEmpty
        - type: InversePosesPre
          probability: 0.1 #0.1
          joint_format: coco
        - type: JointNoise
          std: 0.1 #0.2
        - type: PointNoise
          std: 0.05
        - type: GaitTR_MultiInput
          joint_format: coco
        - type: SkeletonInput
