data_cfg:
  dataset_name: GREW
  dataset_root: ../GREW-PKL
  dataset_partition: ./datasets/GREW/GREW.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: GREW
  frame_threshold: 0

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 195000
  save_name: GagFormer
  eval_func: evaluate_real_scene
  sampler:
    batch_size: 8 #should same to num_gpus
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos
  transform:
    - type: Compose
      trf_cfg:
        - type: GaitTR_MultiInput
          joint_format: coco
        - type: SkeletonInput

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.3
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: GaitGear
  in_c:
    - 10
    - 64
    - 128
    - 128
    - 128
    - 128
    - 256
    - 256
  num_class: 20000
  share_num: 3
  joint_format: coco


optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.00002

scheduler_cfg:
  three_phase: True
  max_lr: 0.001
  div_factor: 100
  total_steps: 200000
  pct_start: 0.475 #学习率上升部分的比例
  scheduler: OneCycleLR

trainer_cfg:
  enable_float16: false #not use
  log_iter: 100
  with_test: false
  restore_ckpt_strict: true
  restore_hint: 150000
  save_iter: 5000
  save_name: GagFormer
  sync_BN: true
  total_iter: 200000
  sampler:
    batch_shuffle: false
    batch_size:
      - 32
      - 8
    frames_num_fixed: 60
    frames_num_max: 50
    frames_num_min: 25
    sample_type: fixed_ordered #Repeat sample
    frames_skip_num: 0 
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: InversePosesPre
          probability: 0.01
        - type: JointNoise
          std: 0.3
        - type: GaitTR_MultiInput
          joint_format: coco
        - type: SkeletonInput
